In [1]:
import numpy as np

In [9]:
list(np.random.rand(128, 1))

[array([0.63382879]),
 array([0.95846911]),
 array([0.19903863]),
 array([0.22064769]),
 array([0.55610643]),
 array([0.23261012]),
 array([0.130823]),
 array([0.73763208]),
 array([0.61619929]),
 array([0.06088015]),
 array([0.38490708]),
 array([0.57235938]),
 array([0.79796944]),
 array([0.2312929]),
 array([0.60355877]),
 array([0.71485606]),
 array([0.28434572]),
 array([0.89243477]),
 array([0.40427565]),
 array([0.64424089]),
 array([0.13525651]),
 array([0.25499166]),
 array([0.92805146]),
 array([0.57469138]),
 array([0.31731099]),
 array([0.1538613]),
 array([0.88094396]),
 array([0.66543233]),
 array([0.79049321]),
 array([0.20095432]),
 array([0.82143837]),
 array([0.76546301]),
 array([0.15876007]),
 array([0.14984507]),
 array([0.30232281]),
 array([0.96649261]),
 array([0.02628168]),
 array([0.04668309]),
 array([0.21188815]),
 array([0.14007478]),
 array([0.92533942]),
 array([0.24943343]),
 array([0.22390618]),
 array([0.83231133]),
 array([0.93238136]),
 array([0.0430